# Generated by Django 3.2.7 on 2021-09-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20210918_1738"),
        ("blog", "0004_alter_comment_id"),
    ]

    operations = []
